apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elkstack
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: http
  type: NodePort
